version: '3'

services:
  app:
    container_name: app
    build:
      context: ./project
      args:
        PROJECT_ENV: development
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./project:/project
    command: uwsgi --http :8000 --wsgi-file /project/config/wsgi.py -M --logto /project/dev.log --py-autoreload 3
    env_file:
      - ./project/.env
      - ./project/.env.development
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: siksa
      POSTGRES_USER: siksa_dev
      POSTGRES_PASSWORD: siksa123!@