version: '3'

services:
  app:
      container_name: app
      tty: true
      build:
        context: ./project
        args:
          PROJECT_ENV: development
      volumes:
        - ./project:/project
