version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: siksa
      POSTGRES_USER: siksa_dev
      POSTGRES_PASSWORD: siksa123!@
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'
