# Generated by Django 2.2.2 on 2019-06-23 07:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='공개 전화번호')),
                ('description', models.TextField(blank=True, null=True, verbose_name='소개')),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(choices=[(0, '취업'), (1, '창업')]), help_text='복수 선택 가능', size=None, verbose_name='카테고리')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '멘토',
                'verbose_name_plural': '멘토들',
                'db_table': 'mentors',
            },
        ),
    ]
