# Generated by Django 2.2.2 on 2019-06-23 07:27

import apps.user.enums
import apps.user.images
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=202, verbose_name='이름')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=apps.user.images.user_profile_image_path, verbose_name='프로필 이미지')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='휴대전화')),
                ('is_phone_authenticate', models.BooleanField(default=False, verbose_name='휴대전화 인증 여부')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='닉네임')),
                ('gender', models.SmallIntegerField(choices=[(0, '남자'), (1, '여자'), (2, '기타')], default=apps.user.enums.Gender(2), verbose_name='성별')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='그룹')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='유저 권한')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='DropUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '탈퇴 유저',
                'verbose_name_plural': '탈퇴 유저들',
                'db_table': 'user_dropusers',
            },
        ),
    ]
